apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  labels:
    app: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service-app
          image: 357586184453.dkr.ecr.us-west-2.amazonaws.com/microservice_question:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: question-service-svc
spec:
  ports:
    - targetPort: 9001
      port: 80
  selector:
    app: question-service