apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  namespace: health-check
  labels:
    app: quiz-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app : quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
      - name: quiz-service
        image: 357586184453.dkr.ecr.us-west-2.amazonaws.com/microservice_quiz:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9002

---

kind: Service
apiVersion: v1
metadata:
  name:  quiz-service-svc
  namespace: health-check
spec:
  selector:
    app:  quiz-service
  ports:
  - port:  80
    targetPort:  9002