apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: health-check
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app : service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: 357586184453.dkr.ecr.us-west-2.amazonaws.com/microservice_service-regstry:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8761

      imagePullSecrets:
        - name: regcred

---

kind: Service
apiVersion: v1
metadata:
  name:  service-registry
  namespace: health-check
spec:
  selector:
    app:  service-registry
  type: NodePort
  ports:
  - port:  80
    targetPort:  8761