apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: 357586184453.dkr.ecr.us-west-2.amazonaws.com/microservice_service-regstry:latest
          ports:
            - containerPort: 8761 # Port on which Eureka server runs
          # You may need to mount a ConfigMap or Secret for configuration if needed
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761 # Port to expose for accessing Eureka server
      targetPort: 8761
  type: NodePort # Exposes the service outside the cluster, you can choose based on your requirement
